CREATE DATABASE MAIEVDATABASE
GO
USE MAIEVDATABASE
GO
CREATE TABLE TB_LE_USUARIO(
	 ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    DS_USUARIO VARCHAR(100) NOT NULL,
    DS_LOGIN VARCHAR(100) NOT NULL,
    DS_SENHA VARCHAR(100) NOT NULL,
    NR_IDADE INT NOT NULL,
    FL_ATIVO BIT NOT NULL,
	FL_ADMINISTRADOR BIT NOT NULL
);
GO
CREATE TABLE TB_LE_PRODUTO(
	ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY,
    DS_NOME VARCHAR(100) NOT NULL,
    VL_PRODUTO DECIMAL(18,2) NOT NULL
);
GO
CREATE TABLE TB_LE_LANCE (
    ID_LANCE INT IDENTITY(1,1) PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    VL_LANCE DECIMAL(18,2) NOT NULL,
    DT_LANCE DATETIME NOT NULL
	CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES TB_LE_USUARIO(ID_USUARIO),
	CONSTRAINT FK_ID_PRODUTO FOREIGN KEY (ID_PRODUTO)
    REFERENCES TB_LE_PRODUTO(ID_PRODUTO)
);
GO
BEGIN
    INSERT INTO TB_LE_USUARIO VALUES ('Willian Vitor','dlhaForense', '2E25E899BDF1E7128F80C5B39161D27839E6140E', 24, 1, 1)
    INSERT INTO TB_LE_PRODUTO VALUES ('Onix',34.962)
    INSERT INTO TB_LE_PRODUTO VALUES ('Cruze',12299000)
    INSERT INTO TB_LE_PRODUTO VALUES ('BMW i8',64995000)
    INSERT INTO TB_LE_PRODUTO VALUES ('BMW M4',50295000)
    INSERT INTO TB_LE_PRODUTO VALUES ('BMW SÉRIE 8',117595000)
    INSERT INTO TB_LE_PRODUTO VALUES ('BMW X5 2021',68995000)
    INSERT INTO TB_LE_PRODUTO VALUES ('JAGUAR XE',32395000)
    INSERT INTO TB_LE_PRODUTO VALUES ('KIA CERATO',9499000)
    INSERT INTO TB_LE_PRODUTO VALUES ('KIA STINGER',34999000)
    INSERT INTO TB_LE_PRODUTO VALUES ('JEEP COMPASS',17290200)
    INSERT INTO TB_LE_PRODUTO VALUES ('JEEP WRANGLER',35385500)
END
GO